import Head from 'next/head'
import AsideMenu from '../components/layouts/AsideMenu'

export default function Tables() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AsideMenu />

      <main>
        테이블 페이지
      </main>
    </div>
  )
}